services:
  postgres:
    image: postgres:16-alpine
    container_name: yava_db
    environment:
      POSTGRES_USER: yava
      POSTGRES_PASSWORD: yava_secret
      POSTGRES_DB: yava_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
