import type { Recipe, RecipeType, User } from '@/types'

export const mockUser: User = {
  id: '1',
  name: 'Revianto',
  email: 'revianto.dev@gmail.com',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=revianto',
}

export const recipeTypes: RecipeType[] = [
  { id: '1', name: 'V60', slug: 'v60' },
  { id: '2', name: 'Espresso', slug: 'espresso' },
  { id: '3', name: 'Chemex', slug: 'chemex' },
  { id: '4', name: 'Aeropress', slug: 'aeropress' },
  { id: '5', name: 'French Press', slug: 'french-press' },
  { id: '6', name: 'Moka Pot', slug: 'moka-pot' },
]

export const mockRecipes: Recipe[] = [
  {
    id: '1',
    typeId: '1',
    typeName: 'V60',
    subtypeName: 'Pour Over',
    title: 'V60 Classic — 4:6 Method',
    description: 'Metode 4:6 dari Tetsu Kasuya. Mudah dikontrol, konsisten, dan bisa disesuaikan ke sweet atau bright.',
    coffeeBeans: 'Ethiopia Yirgacheffe',
    coffeeGrams: 20,
    waterMl: 300,
    grindSize: 'Medium-coarse',
    waterTempC: 93,
    visibility: 'public',
    isDefault: true,
    isArchived: false,
    totalDurationSeconds: 210,
    createdAt: '2024-01-15T08:00:00Z',
    sessions: [
      { id: 's1', recipeId: '1', order: 1, label: 'Bloom', durationSeconds: 45, waterMl: 60, notes: 'Tuang merata, tunggu bloom' },
      { id: 's2', recipeId: '1', order: 2, label: 'Pour 1', durationSeconds: 45, waterMl: 60 },
      { id: 's3', recipeId: '1', order: 3, label: 'Pour 2', durationSeconds: 45, waterMl: 60 },
      { id: 's4', recipeId: '1', order: 4, label: 'Pour 3', durationSeconds: 45, waterMl: 60 },
      { id: 's5', recipeId: '1', order: 5, label: 'Pour 4', durationSeconds: 30, waterMl: 60 },
    ],
    notes: [
      { id: 'n1', recipeId: '1', order: 6, content: 'Pastikan filter sudah dibilas dengan air panas sebelum mulai.' },
    ],
  },
  {
    id: '2',
    typeId: '2',
    typeName: 'Espresso',
    title: 'Espresso Double Shot',
    description: 'Standard double shot espresso. Rasio 1:2, waktu ekstraksi 25–30 detik.',
    coffeeBeans: 'Brazil Santos Blend',
    coffeeGrams: 18,
    waterMl: 36,
    grindSize: 'Fine',
    waterTempC: 92,
    visibility: 'private',
    isDefault: false,
    isArchived: false,
    totalDurationSeconds: 30,
    createdAt: '2024-02-10T09:00:00Z',
    sessions: [
      { id: 's6', recipeId: '2', order: 1, label: 'Pre-infusion', durationSeconds: 5, notes: '3–5 bar' },
      { id: 's7', recipeId: '2', order: 2, label: 'Extraction', durationSeconds: 25, notes: '9 bar' },
    ],
    notes: [],
  },
  {
    id: '3',
    typeId: '3',
    typeName: 'Chemex',
    title: 'Chemex Weekend Brew',
    description: 'Slow brew untuk weekend. Clean cup, jernih, dan floral.',
    coffeeBeans: 'Colombia Huila',
    coffeeGrams: 30,
    waterMl: 500,
    grindSize: 'Coarse',
    waterTempC: 95,
    visibility: 'public',
    isDefault: false,
    isArchived: false,
    totalDurationSeconds: 300,
    createdAt: '2024-03-05T07:30:00Z',
    sessions: [
      { id: 's8', recipeId: '3', order: 1, label: 'Bloom', durationSeconds: 60, waterMl: 90 },
      { id: 's9', recipeId: '3', order: 2, label: 'First Pour', durationSeconds: 120, waterMl: 200 },
      { id: 's10', recipeId: '3', order: 3, label: 'Second Pour', durationSeconds: 120, waterMl: 210 },
    ],
    notes: [
      { id: 'n2', recipeId: '3', order: 4, content: 'Gunakan filter Chemex asli untuk hasil terbaik.' },
      { id: 'n3', recipeId: '3', order: 5, content: 'Total brew time sekitar 4–5 menit.' },
    ],
  },
  {
    id: '4',
    typeId: '4',
    typeName: 'Aeropress',
    title: 'Aeropress Inverted',
    description: 'Teknik inverted untuk kontrol penuh. Full immersion, hasil bold.',
    coffeeBeans: 'Guatemala Antigua',
    coffeeGrams: 15,
    waterMl: 200,
    grindSize: 'Medium',
    waterTempC: 80,
    visibility: 'private',
    isDefault: false,
    isArchived: false,
    totalDurationSeconds: 150,
    createdAt: '2024-03-20T10:00:00Z',
    sessions: [
      { id: 's11', recipeId: '4', order: 1, label: 'Bloom', durationSeconds: 30, waterMl: 30 },
      { id: 's12', recipeId: '4', order: 2, label: 'Fill', durationSeconds: 60, waterMl: 170 },
      { id: 's13', recipeId: '4', order: 3, label: 'Stir & Press', durationSeconds: 60 },
    ],
    notes: [],
  },
  {
    id: '5',
    typeId: '1',
    typeName: 'V60',
    title: 'V60 Light Roast Bright',
    description: 'Untuk single origin light roast. Acidity ditonjolkan.',
    coffeeBeans: 'Kenya AA',
    coffeeGrams: 15,
    waterMl: 250,
    grindSize: 'Medium',
    waterTempC: 96,
    visibility: 'public',
    isDefault: false,
    isArchived: true,
    totalDurationSeconds: 180,
    createdAt: '2024-04-01T06:00:00Z',
    sessions: [
      { id: 's14', recipeId: '5', order: 1, label: 'Bloom', durationSeconds: 45, waterMl: 45 },
      { id: 's15', recipeId: '5', order: 2, label: 'Main Pour', durationSeconds: 135, waterMl: 205 },
    ],
    notes: [],
  },
]
