[build]
  cmd = "go build -o ./tmp/main ."
  entrypoint = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "public"]
  delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
